version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: laboratory-mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: laboratory
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
#      TZ: Asia/Seoul
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
